rm(list=ls(all=TRUE)) #clears memory

means = runif(5, min=-5, max=5)

one1 = pnorm(means[1]+1, mean=means[1], sd=1) - pnorm(means[1]-1, mean=means[1], sd=1)
one2 = pnorm(means[2]+1, mean=means[2], sd=1) - pnorm(means[2]-1, mean=means[2], sd=1)
one3 = pnorm(means[3]+1, mean=means[3], sd=1) - pnorm(means[3]-1, mean=means[3], sd=1)
one4 = pnorm(means[4]+1, mean=means[4], sd=1) - pnorm(means[4]-1, mean=means[4], sd=1)
one5 = pnorm(means[5]+1, mean=means[5], sd=1) - pnorm(means[5]-1, mean=means[5], sd=1)
print("Within one standard deviation: ")
print(one1)
print(one2)
print(one3)
print(one4)
print(one5)

two1 = pnorm(means[1]+(2^2), mean=means[1], sd=2) - pnorm(means[1]-(2^2), mean=means[1], sd=2)
two2 = pnorm(means[2]+(2^2), mean=means[2], sd=2) - pnorm(means[2]-(2^2), mean=means[2], sd=2)
two3 = pnorm(means[3]+(2^2), mean=means[3], sd=2) - pnorm(means[3]-(2^2), mean=means[3], sd=2)
two4 = pnorm(means[4]+(2^2), mean=means[4], sd=2) - pnorm(means[4]-(2^2), mean=means[4], sd=2)
two5 = pnorm(means[5]+(2^2), mean=means[5], sd=2) - pnorm(means[5]-(2^2), mean=means[5], sd=2)
print("Within two standard deviations: ")
print(two1)
print(two2)
print(two3)
print(two4)
print(two5)

three1 = pnorm(means[1]+(3^2), mean=means[1], sd=3) - pnorm(means[1]-(3^2), mean=means[1], sd=3)
three2 = pnorm(means[2]+(3^2), mean=means[2], sd=3) - pnorm(means[2]-(3^2), mean=means[2], sd=3)
three3 = pnorm(means[3]+(3^2), mean=means[3], sd=3) - pnorm(means[3]-(3^2), mean=means[3], sd=3)
three4 = pnorm(means[4]+(3^2), mean=means[4], sd=3) - pnorm(means[4]-(3^2), mean=means[4], sd=3)
three5 = pnorm(means[5]+(3^2), mean=means[5], sd=3) - pnorm(means[5]-(3^2), mean=means[5], sd=3)
print("Within three standard deviations: ")
print(three1)
print(three2)
print(three3)
print(three4)
print(three5)